### ISSUE TITLE
Create spring security

### ISSUE THREAD

**Issue by andronisdre** [andronisdre/SpeedAuctionBackend#16]
- [ ] Create spring security
- [ ] create a security folder
- [ ] create a jwt folder in security folder
- [ ] create AuthenticationEntryJwt in jwt 
- [ ] create AuthTokenFilter in jwt 
- [ ] create JwtUtils in jwt 
- [ ] create a services folder in security folder
- [ ] create UserDetailsImpl in services
- [ ] create UserDetailsServiceImpl in services
